#
# Ensure the appropriate command has been executed
# export LIBRARY_PATH=../../../lib64
# export LIBRARY_PATH=../../../lib
#
name = "libxl"
version = "4.2.0"
author = "XLware"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[[example]]
name = "generate"
source-dir = "generate"
main = "generate.f90"
link = 'xl'
[[example]]
name = "extract"
source-dir = "extract"
main = "extract.f90"
link = 'xl'
[[example]]
name = "invoice"
source-dir = "invoice"
main = "invoice.f90"
link = 'xl'
[[example]]
name = "custom"
source-dir = "custom"
main = "custom.f90"
link = 'xl'
[[example]]
name = "edit"
source-dir = "edit"
main = "edit.f90"
link = 'xl'
[[example]]
name = "format"
source-dir = "format"
main = "format.f90"
link = 'xl'

